name: Populate Depot json

on: 
  release:
  workflow_dispatch:

jobs:
  populate:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: meisZWFLZ/pros-depot-from-releases@b128d85e74ffe549c2319fc9b5fe73352cad8df2
        with:
          token: ${{ github.token }}
          repo: meiszwflz/LemLib
