name: Populate Depot json

on: 
  release:
  workflow_dispatch:

jobs:
  populate:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: meisZWFLZ/pros-depot-from-releases@e73227af81548cc02c132877661a9fa7723acb46
        with:
          token: ${{ github.token }}
          repo: ${{ github.context.repo }}
