name: Populate Depot json

on: 
  release:
  workflow_dispatch:

jobs:
  populate:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: meisZWFLZ/pros-depot-from-releases@dbaa18709f8239296212a47328a221290bd31fd8
        with:
          token: ${{ github.token }}
          repo: meiszwflz/LemLib
          source-repo: LemLib/LemLib
          readable-json: true
