name: Populate Depot json

on: 
  release:
  workflow_dispatch:

jobs:
  populate:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: meisZWFLZ/pros-depot-from-releases@401feb7f4b13e9b7f4f2265775e0cf4afa976974
        with:
          token: ${{ github.token }}
          repo: meiszwflz/LemLib
