name: Populate Depot json

on: 
  release:
  workflow_dispatch:

jobs:
  populate:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: meisZWFLZ/pros-depot-from-releases@b8fc2a969ab12b2cb78eaa0a4ca9af55bc2eeb89
        with:
          token: ${{ github.token }}
          repo: ${{ github.context.repo }}
