name: Populate Depot json

on: 
  release:
  workflow_dispatch:

jobs:
  populate:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: meisZWFLZ/pros-depot-from-releases@43f29d092b90a253bcc952ceb7a05ed6ba668a67
        with:
          token: ${{ github.token }}
          repo: meiszwflz/LemLib
          source-repo: LemLib/LemLib
          readable: true
