name: Populate Depot json

on: 
  release:
  workflow_dispatch:

jobs:
  populate:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: meisZWFLZ/pros-depot-from-releases@12c2ff5f5dfa7a3d5dbab970dd0f8a86cb9d3235
        with:
          token: ${{ github.token }}
          repo: meiszwflz/LemLib
