name: Populate Depot json

on: 
  release:
  workflow_dispatch:

jobs:
  populate:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: meisZWFLZ/pros-depot-from-releases@5d403a6bab3cb082edff63b1151a23b4f257ed9d
        with:
          token: ${{ github.token }}
          repo: ${{ github.context.repo }}
