name: run-unit-tests
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt install build-essential
          sudo apt install cmake
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: Test
        run: |
        working-directory: build
        run: ./LemLib
